// ACTION TYPES
export const TASKS = 'TASKS'

export const DELETE_TASK = 'DELETE_TASK'

export const NEW_TASK = 'NEW_TASK'

export const UPDATE_TASK = 'UPDATE_TASK'

// MUTATION TYPES
export const TASKS_REQUEST = 'TASKS REQUEST'
export const TASKS_RESPONSE = 'TASKS RESPONE'
export const TASKS_ERRORS = 'TASKS ERRORS'

export const SINGLE_TASK_RESPONSE = 'SINGLE_TASK_RESPONSE'

export const DELETE_TASK_REQUEST = 'DELETE_TASK REQUEST'
export const DELETE_TASK_RESPONSE = 'DELETE_TASK RESPONSE'
export const DELETE_TASK_ERRORS = 'DELETE_TASK ERRORS'

export const NEW_TASK_REQUEST = 'NEW_TASK REQUEST'
export const NEW_TASK_RESPONSE = 'NEW_TASK RESPONSE'
export const NEW_TASK_ERRORS = 'NEW_TASK ERRORS'

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK REQUEST'
export const UPDATE_TASK_RESPONSE = 'UPDATE_TASK RESPONSE'
export const UPDATE_TASK_ERRORS = 'UPDATE_TASK ERRORS'

